### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CDr-er** [Kjplay/Twine-Harlowe-Save-To_File#4]
Just a quick question! Does this still work in Harlowe 3.2.3, or have the updates broken it? I ask as whenever I try to load I get the following error:

```
Sorry to interrupt, but this page's code has got itself in a mess.
ReferenceError: Selectors is not defined
ReferenceError: Selectors is not defined

(This is probably due to a bug in the Harlowe game engine.)
```

If the Harlowe updates have broken this, do you intend to update this? (_please say yes this code is amazing_)

**Comment by Kajot-dev** [comment]
I can make an update if you want. However, keep in mind that saves from 3.1.0 won't work in 3.2.3+ (they're just incompatible). I'll make a separate branch for it and let you know here, when it's done :)

**Comment by Kajot-dev** [comment]
Now it should work with 3.2.0+ (but sadly not with 3.1.0 anymore :)

**Comment by CDr-er** [comment]
Thank you so much for this! I would have no idea where to start with that JS so you've saved me the pain of learning it myself! Very much appreciated :D
