### ISSUE TITLE
Compatibility 3.3.1?

### ISSUE THREAD

**Issue by OscarArcane** [Kjplay/Twine-Harlowe-Save-To_File#7]
Hello, I just discovered this code and got very excited to be able to have a save-to-file function in Harlowe so thank you for your work!
I wasn't able to make it work, however, and I wondered if it was because it was not compatible with Harlowe 3.3.1?

**Comment by Kajot-dev** [comment]
It is entirely possible, I'll look into the compatibility.

**Comment by Kajot-dev** [comment]
@OscarArcane It should now be compatible with Harlowe 3.3.x (tested with 3.3.7)

**Comment by OscarArcane** [comment]
Thank you! I tried it out and it works great! Although in the readme it says that the macro to load the file is (loadfromfile:) when it actually is (readfromfile:) so I thought I would give you a heads up.
