### ISSUE TITLE
Compatibility with 3.3.7

### ISSUE THREAD

**Issue by MrChimaz** [Kjplay/Twine-Harlowe-Save-To_File#8]
Hi, I hope everything is going well!
I discovered your macros recently and was eager to try them out, but unfortunately they are not compatible with Harlowe 3.3.7.
I was wondering if you could be so kind as to make them compatible with the latest version of Harlowe.
Thanks in advance!

**Comment by Kajot-dev** [comment]
Yup I will try to make a couple versions, each compatible with different harlowe version

**Comment by Kajot-dev** [comment]
@MrChimaz I've published a new release which should now be compatible with Harlowe 3.3.7
